version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/app
      - /app/vendor
      - /app/.bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling
    
  # Alternative service using official Jekyll image
  jekyll-official:
    image: jekyll/jekyll:4.2.0
    ports:
      - "4001:4000"
      - "35730:35729"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --livereload --force_polling
    profiles:
      - alternative